version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net
networks:
  laravel-net:

